services:
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - '3307:3306'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: '${DB_DATABASE:-keel}'
        volumes:
            - keel-mysql-data:/var/lib/mysql
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-h'
                - '127.0.0.1'
            retries: 5
            timeout: 5s

volumes:
    keel-mysql-data:
        driver: local
